# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 08:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.CharField(max_length=100, unique=True)),
                ('m_depart', models.CharField(blank=True, max_length=200)),
                ('m_bed', models.CharField(blank=True, max_length=200)),
                ('m_xinfei', models.CharField(default='1', max_length=30)),
                ('m_naoxueguan', models.CharField(default='1', max_length=30)),
                ('m_chidai', models.CharField(default='1', max_length=30)),
                ('m_piantan', models.CharField(default='1', max_length=30)),
                ('m_xueya', models.CharField(default='1', max_length=30)),
                ('m_guanxinbin', models.CharField(default='1', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=100, unique=True)),
                ('p_name', models.CharField(blank=True, max_length=100)),
                ('p_sname', models.CharField(blank=True, max_length=100)),
                ('p_dob', models.DateField(blank=True, default=datetime.datetime(2016, 8, 4, 16, 49, 58, 366000))),
                ('p_age', models.IntegerField(blank=True, default=0)),
                ('p_height', models.DecimalField(decimal_places=2, max_digits=8)),
                ('p_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('p_marriage', models.CharField(blank=True, max_length=10)),
                ('p_edu', models.CharField(blank=True, max_length=10)),
                ('p_loc', models.CharField(blank=True, max_length=400)),
                ('p_cell1', models.CharField(blank=True, max_length=50)),
                ('p_cell2', models.CharField(blank=True, max_length=50)),
                ('p_idcard', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_id', models.CharField(max_length=100, unique=True)),
                ('prj_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelPrjMedPat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_mdepart', models.CharField(blank=True, max_length=50)),
                ('r_pname', models.CharField(blank=True, max_length=50)),
                ('r_mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmid', to='crfapp.MedicalBase', to_field='m_id')),
                ('r_pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpid', to='crfapp.Patient', to_field='p_id')),
                ('r_prjid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rprjid', to='crfapp.Project', to_field='prj_id')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('depart', models.CharField(blank=True, max_length=200)),
                ('cell', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
