# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 14:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crfapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='p_dob',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 8, 4, 22, 22, 41, 459000)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
