# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crfapp', '0002_auto_20160804_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='p_dob',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 8, 4, 22, 26, 5, 414000)),
        ),
        migrations.AlterField(
            model_name='relprjmedpat',
            name='r_prjid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crfapp.Project'),
        ),
    ]
