# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-05 01:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crfapp', '0003_auto_20160804_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='p_dob',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 8, 5, 9, 56, 15, 795000)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_marriage',
            field=models.CharField(blank=True, default=1, max_length=10),
        ),
    ]
