# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-05 02:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crfapp', '0004_auto_20160805_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_dob',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 8, 5, 10, 1, 3, 500000)),
        ),
    ]
