# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depotapp', '0002_product_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='date_available',
        ),
    ]
